/*	$NetBSD$	*/

/*-
 * Copyright (c) 2025 Hiroki Mori
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *	notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *	notice, this list of conditions and the following disclaimer in the
 *	documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
 * IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#define XIN_CLK_RATE		240000		// 24MHz
#define XTIN_CLK_RATE		327		// 32.768kHz
#define HDMI_CLK_RATE		270000

#define CKC_DISABLE		0
#define CKC_ENABLE		1
#define CKC_NOCHANGE		2

#define CKC_BASE				HwCKC_BASE
#define REG_CLKCTRL		0x000
#define REG_PLL			0x030
#define REG_CLKDIVC		0x050
#define REG_SWRESET		0x064
#define REG_PCLKCTRL		0x080
//#define PMU_BASE				HwPMU_BASE
//#define REG_IPPWDN			  io_p2v(PMU_BASE+0x05C)

#define PLL_VCO_MAX		(2000*10000)
#define PLL_VCO_MIN		(1000*10000)
#define PLL_VCO_SEL		(1400*10000)
#define PLL_P_MAX		63
#define PLL_P_MIN		1
#define PLL_P_SHIFT		0
#define PLL_P_MASK		PLL_P_MAX
#define PLL_M_MAX		1023
#define PLL_M_MIN		16
#define PLL_M_SHIFT		8
#define PLL_M_MASK		PLL_M_MAX
#define PLL_S_MAX		5
#define PLL_S_MIN		0
#define PLL_S_SHIFT		24
#define PLL_S_MASK		0x7
#define PLL_SRC_SHIFT		18
#define PLL_SRC_MASK		0x3
#define PLL_LOCKEN_SHIFT	20
#define PLL_LOCKST_SHIFT	21
#define PLL_LOCK_MASK		0x1
#define PLL_VSEL_SHIFT		30
#define PLL_VSEL_MASK		0x1
#define PLL_EN_SHIFT		31
#define PLL_EN_MASK		0x1

typedef enum { /* PCLK Type */
	PCLKCTRL_TYPE_XXX=0,
	PCLKCTRL_TYPE_YYY,
	PCLKCTRL_TYPE_ZZZ,
	PCLKCTRL_TYPE_MAX
} tPCLKTYPE;

enum { /* PCLK Mode Selection */
	PCLKCTRL_MODE_DCO=0,
	PCLKCTRL_MODE_DIVIDER,
	PCLKCTRL_MODE_MAX
};

enum{ /* Peri. Clock Source */
	PCLKCTRL_SEL_PLL0=0,
	PCLKCTRL_SEL_PLL1,
	PCLKCTRL_SEL_PLL2,
	PCLKCTRL_SEL_PLL3,
	PCLKCTRL_SEL_XIN,
	PCLKCTRL_SEL_PLL0DIV,			// 5
	PCLKCTRL_SEL_PLL1DIV,
	PCLKCTRL_SEL_PLL2DIV,
	PCLKCTRL_SEL_PLL3DIV,
	PCLKCTRL_SEL_XTIN,
	PCLKCTRL_SEL_HDMITMDS=11,
	PCLKCTRL_SEL_HDMIPCLK,
	PCLKCTRL_SEL_HDMIXIN, // 27Mhz
	PCLKCTRL_SEL_XINDIV=16,
	PCLKCTRL_SEL_XTINDIV,
	PCLKCTRL_SEL_PLL4,
	PCLKCTRL_SEL_PLL5,
	PCLKCTRL_SEL_PLL4DIV,			// 20
	PCLKCTRL_SEL_PLL5DIV,
	PCLKCTRL_SEL_EXTCLK0=23,
	PCLKCTRL_SEL_EXTCLK1,
};

typedef struct {
	unsigned int	fpll;
	unsigned int	en;
	unsigned int	p;
	unsigned int	m;
	unsigned int	s;
	unsigned int	vsel;
	unsigned int	src;
} tPMS;

/* PLL Clock Source */
enum{
	PLLSRC_XIN=0,
	PLLSRC_HDMIXI,
	PLLSRC_EXTCLK0,
	PLLSRC_EXTCLK1,
	PLLSRC_MAX
};

/* Peripheral Clocks */
enum {/* Peri. Name */
	PERI_TCX = 0,		// 0	// 0x80
	PERI_TCT,
	PERI_TCZ,
	PERI_LCD0,
	PERI_LCDSI0,
	PERI_LCD1,		// 5
	PERI_LCDSI1,
	PERI_RESERVED07,
	PERI_LCDTIMER,
#if defined(CONFIG_CHIP_TCC8935S) || defined(CONFIG_CHIP_TCC8933S) || defined(CONFIG_CHIP_TCC8937S)
	PERI_JPEG,
#else
	PERI_RESERVED09,
#endif
	PERI_RESERVED10,	// 10
	PERI_RESERVED11,
	PERI_GMAC,
	PERI_USBOTG,
	PERI_RESERVED14,
	PERI_OUT0,		// 15
	PERI_USB20H,
	PERI_HDMI,
	PERI_HDMIA,
	PERI_OUT1,
#if defined(CONFIG_CHIP_TCC8935S) || defined(CONFIG_CHIP_TCC8933S) || defined(CONFIG_CHIP_TCC8937S)
	PERI_EHI,
#else
	PERI_REMOTE,		// 20
#endif
	PERI_SDMMC0,
#if defined(CONFIG_CHIP_TCC8935S) || defined(CONFIG_CHIP_TCC8933S) || defined(CONFIG_CHIP_TCC8937S)
	PERI_RESERVED22,
#else
	PERI_SDMMC1,
#endif
	PERI_SDMMC2,
	PERI_SDMMC3,
	PERI_ADAI1,		// 25
	PERI_ADAM1,
	PERI_SPDIF1,
	PERI_ADAI0,
	PERI_ADAM0,
#if defined(CONFIG_CHIP_TCC8935S) || defined(CONFIG_CHIP_TCC8933S) || defined(CONFIG_CHIP_TCC8937S)
	PERI_RESERVED30,
#else
	PERI_SPDIF0,		// 30
#endif
	PERI_PDM,
	PERI_RESERVED32,
	PERI_ADC,
	PERI_I2C0,
	PERI_I2C1,		// 35
	PERI_I2C2,
	PERI_I2C3,
	PERI_UART0,
	PERI_UART1,
	PERI_UART2,		// 40
	PERI_UART3,
#if defined(CONFIG_CHIP_TCC8935S) || defined(CONFIG_CHIP_TCC8933S) || defined(CONFIG_CHIP_TCC8937S)
	PERI_RESERVED42,
	PERI_RESERVED43,
	PERI_RESERVED44,
	PERI_RESERVED45,
#else
	PERI_UART4,
	PERI_UART5,
	PERI_UART6,
	PERI_UART7,		// 45
#endif
	PERI_GPSB0,
	PERI_GPSB1,
	PERI_GPSB2,
#if !defined(CONFIG_CHIP_TCC8935S) && !defined(CONFIG_CHIP_TCC8933S) && !defined(CONFIG_CHIP_TCC8937S)
	PERI_GPSB3,
	PERI_GPSB4,		// 50
	PERI_GPSB5,
	PERI_CAN0,
	PERI_CAN1,
	PERI_OUT2,
	PERI_OUT3,		// 55
	PERI_OUT4,
	PERI_OUT5,
	PERI_TSTX0,
	PERI_TSTX1,
	PERI_PKTGEN0,		// 60
	PERI_PKTGEN1,
	PERI_PKTGEN2,
	PERI_PKTGEN3,
#endif
	PERI_MAX,
};

#if defined(CONFIG_CHIP_TCC8933S) || defined(CONFIG_CHIP_TCC8935S) || defined(CONFIG_CHIP_TCC8937S)
#define MAX_TCC_PLL		 4
#else
#define MAX_TCC_PLL		 6
#endif
#define MAX_CLK_SRC		 (MAX_TCC_PLL*2 + 1)	 // XIN

/* PeriPheral Clocks */
#define PCLKCTRL_DIV_MIN	0
#define PCLKCTRL_DIV_DCO_MIN	1
#define PCLKCTRL_DIV_SHIFT	0
#define PCLKCTRL_DIV_XXX_MAX	0xFFF
#define PCLKCTRL_DIV_XXX_MASK	PCLKCTRL_DIV_XXX_MAX
#define PCLKCTRL_DIV_YYY_MAX	0xFFFF
#define PCLKCTRL_DIV_YYY_MASK	PCLKCTRL_DIV_YYY_MAX
#define PCLKCTRL_DIV_ZZZ_MAX	0xFFFFFF
#define PCLKCTRL_DIV_ZZZ_MASK	PCLKCTRL_DIV_ZZZ_MAX
#define PCLKCTRL_SEL_MIN	0
#define PCLKCTRL_SEL_MAX	31
#define PCLKCTRL_SEL_SHIFT	24
#define PCLKCTRL_SEL_MASK	PCLKCTRL_SEL_MAX
#define PCLKCTRL_EN_SHIFT	29
#define PCLKCTRL_EN_MASK	0x1
#define PCLKCTRL_MD_SHIFT	31
#define PCLKCTRL_MD_MASK	0x1

/* PLL channel index */
enum {
	PLL_0=0,
	PLL_1,
	PLL_2,
	PLL_3,
	PLL_4,
	PLL_5,
};

typedef struct {
	unsigned int	periname;
	unsigned int	freq;
	unsigned int	md;
	unsigned int	en;
	unsigned int	sel;
	unsigned int	div;
} tPCLKCTRL;

#define CPU_SRC_CH		0
#define CPU_SRC_PLL		CLKCTRL_SEL_PLL0
#if defined (CONFIG_AUDIO_PLL_USE)
#define AUDIO_SRC_CH	3
#define AUDIO_SRC_PCLK		CLKCTRL_SEL_PLL3
#endif

typedef struct {
	unsigned int	freq;
	unsigned int	en;
	unsigned int	config;
	unsigned int	sel;
} tCLKCTRL;

/* CLKCTRL */
#define CLKCTRL_SEL_MIN		0
#define CLKCTRL_SEL_MAX		15
#define CLKCTRL_SEL_SHIFT	0
#define CLKCTRL_SEL_MASK	CLKCTRL_SEL_MAX
#define CLKCTRL_CONFIG_MIN	1
#define CLKCTRL_CONFIG_MAX	15
#define CLKCTRL_CONFIG_SHIFT	4
#define CLKCTRL_CPU_MASK	0xFFFF
#define CLKCTRL_CONFIG_MASK	0xFFFF //CLKCTRL_CONFIG_MAX
#define CLKCTRL_EN_SHIFT	21
#define CLKCTRL_EN_MASK		0x1
#define CLKCTRL_CFGRQ_SHIFT	29
#define CLKCTRL_CHGRQ_SHIFT	31

enum { /* CLKCTRL SEL */
	CLKCTRL_SEL_PLL0=0,
	CLKCTRL_SEL_PLL1,
	CLKCTRL_SEL_PLL2,
	CLKCTRL_SEL_PLL3,
	CLKCTRL_SEL_XIN,
	CLKCTRL_SEL_PLL0DIV,
	CLKCTRL_SEL_PLL1DIV,
	CLKCTRL_SEL_XTIN,
	CLKCTRL_SEL_PLL4,
	CLKCTRL_SEL_PLL5,
	CLKCTRL_SEL_PLL2DIV,
	CLKCTRL_SEL_PLL3DIV,
	CLKCTRL_SEL_PLL4DIV,
	CLKCTRL_SEL_PLL5DIV,
	CLKCTRL_SEL_XINDIV,
	CLKCTRL_SEL_XTINDIV,
};

/* CLKCTRL channel index */
enum {
	FBUS_CPU = 0,	 	// CLKCTRL0
	FBUS_MEM,	 	// CLKCTRL1
	FBUS_DDI,		// CLKCTRL2
	FBUS_GPU,		// CLKCTRL3
	FBUS_IO,		// CLKCTRL4
	FBUS_VBUS,		// CLKCTRL5
	FBUS_VCORE,		// CLKCTRL6
	FBUS_HSIO,		// CLKCTRL7
	FBUS_SMU,		// CLKCTRL8
#if !defined(CONFIG_CHIP_TCC8935S) && !defined(CONFIG_CHIP_TCC8933S) && !defined(CONFIG_CHIP_TCC8937S)
	FBUS_G2D,		// CLKCTRL9
	FBUS_CM3,		// CLKCTRL10
#endif
};
